### PR TITLE
Update sanchonet conway-genesis for respin

### PR DESCRIPTION
**Pull request by johnalotoski**

### CODE REVIEW

**Review by Crypto2099 — APPROVED** [review]
LGTM

**Review by Ryun1 — APPROVED** [review]

**Comment by kevinhammond** [comment]
Note that the DRep voting thresholds both need to be 65%...

“committeeNoConfidence”: 0.6

**Review by kevinhammond — CHANGES_REQUESTED** [review]
The DRep voting thresholds both need to be 65%
`“committeeNoConfidence”: 0.6`

**Comment by disassembler** [comment]
addressed @kevinhammond comments. Also made a bunch of changes with Johnny Kelly where it differed from recommendation.

Purposefully set govActionLifetime *above* the guardrail because of the short epochs
Purposefully set minCommitteeSize to 5 (from recommended 7) because only 5 ICC members were able to provide keys for the respin.

**Pull request merged**
