### PR TITLE
Bump nixpkgs

### PR DESCRIPTION
**Pull request by andreabedini**
* python37 is gone, replace with python3

### CODE REVIEW

**Review by angerman — APPROVED** [review]
LGTM, but why the flake.lock update?

**Comment by angerman** [comment]
Bors try

**Comment by andreabedini** [comment]
> LGTM, but why the flake.lock update?

because it works with the old nixpkgs but not with the newer one. Consumers are likely to do
```
    iohkNix = {
      url = "github:input-output-hk/iohk-nix";
      inputs.nixpkgs.follows = "nixpkgs";
    };
```
so better test with a new nixpkgs. Am I wrong?

**Comment by angerman** [comment]
> > LGTM, but why the flake.lock update?
> 
> 
> 
> because it works with the old nixpkgs but not with the newer one. Consumers are likely to do
> 
> ```
> 
>     iohkNix = {
> 
>       url = "github:input-output-hk/iohk-nix";
> 
>       inputs.nixpkgs.follows = "nixpkgs";
> 
>     };
> 
> ```
> 
> so better test with a new nixpkgs. Am I wrong?

You are not. It just didn't say in the PR :-)

**Pull request merged**
